# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_cards.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_card(object):
    def setupUi(self, add_card):
        add_card.setObjectName("add_card")
        add_card.resize(552, 413)
        self.verticalLayout = QtWidgets.QVBoxLayout(add_card)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(add_card)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.add_single_card = QtWidgets.QWidget()
        self.add_single_card.setObjectName("add_single_card")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.add_single_card)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.card_info = QtWidgets.QScrollArea(self.add_single_card)
        self.card_info.setStyleSheet("QScrollArea{\n"
"    background: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"/*Vertical*/\n"
"QScrollBar:vertical {\n"
"       border: 0;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"/*Horizontal*/\n"
"QScrollBar:horizontal {\n"
"       border: 0;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}")
        self.card_info.setWidgetResizable(True)
        self.card_info.setObjectName("card_info")
        self.card_info_widget = QtWidgets.QWidget()
        self.card_info_widget.setGeometry(QtCore.QRect(0, 0, 504, 302))
        self.card_info_widget.setStyleSheet("/*Vertical*/\n"
"QScrollBar:vertical {\n"
"       border: 0;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"/*Horizontal*/\n"
"QScrollBar:horizontal {\n"
"       border: 0;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}")
        self.card_info_widget.setObjectName("card_info_widget")
        self.formLayout = QtWidgets.QFormLayout(self.card_info_widget)
        self.formLayout.setObjectName("formLayout")
        self.front_label = QtWidgets.QLabel(self.card_info_widget)
        self.front_label.setObjectName("front_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.front_label)
        self.front_box = QtWidgets.QTextEdit(self.card_info_widget)
        self.front_box.setMinimumSize(QtCore.QSize(0, 100))
        self.front_box.setStyleSheet("background-color: #d3d3d3;\n"
"border-radius: 10px;\n"
"border: 1px solid #d3d3d3;\n"
"padding: 5px;")
        self.front_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.front_box.setAcceptRichText(True)
        self.front_box.setPlaceholderText("")
        self.front_box.setObjectName("front_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.front_box)
        self.back_label = QtWidgets.QLabel(self.card_info_widget)
        self.back_label.setObjectName("back_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.back_label)
        self.back_box = QtWidgets.QTextEdit(self.card_info_widget)
        self.back_box.setMinimumSize(QtCore.QSize(0, 100))
        self.back_box.setStyleSheet("background-color: #d3d3d3;\n"
"border-radius: 10px;\n"
"border: 1px solid #d3d3d3;\n"
"padding: 5px;")
        self.back_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.back_box.setAcceptRichText(True)
        self.back_box.setPlaceholderText("")
        self.back_box.setObjectName("back_box")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.back_box)
        self.image_label = QtWidgets.QLabel(self.card_info_widget)
        self.image_label.setObjectName("image_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.image_label)
        self.choose_image = QtWidgets.QPushButton(self.card_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_image.sizePolicy().hasHeightForWidth())
        self.choose_image.setSizePolicy(sizePolicy)
        self.choose_image.setStyleSheet("QPushButton{\n"
"    /*background: #d3d3d3;*/\n"
"    background: white;\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}\n"
"")
        self.choose_image.setObjectName("choose_image")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.choose_image)
        self.img = QtWidgets.QLabel(self.card_info_widget)
        self.img.setText("")
        self.img.setObjectName("img")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.img)
        self.card_info.setWidget(self.card_info_widget)
        self.verticalLayout_3.addWidget(self.card_info)
        self.button_frame_2 = QtWidgets.QFrame(self.add_single_card)
        self.button_frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.button_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame_2.setObjectName("button_frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.button_frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.save_button_single = QtWidgets.QPushButton(self.button_frame_2)
        self.save_button_single.setStyleSheet("QPushButton{\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"    color: white;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}")
        self.save_button_single.setObjectName("save_button_single")
        self.horizontalLayout_2.addWidget(self.save_button_single)
        self.cancel_button_single = QtWidgets.QPushButton(self.button_frame_2)
        self.cancel_button_single.setStyleSheet("QPushButton{\n"
"    background-color: #d3d3d3;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #a1a1a1;\n"
"    color: white;\n"
"}\n"
"")
        self.cancel_button_single.setObjectName("cancel_button_single")
        self.horizontalLayout_2.addWidget(self.cancel_button_single)
        self.verticalLayout_3.addWidget(self.button_frame_2)
        self.tabWidget.addTab(self.add_single_card, "")
        self.add_multiple_cards = QtWidgets.QWidget()
        self.add_multiple_cards.setObjectName("add_multiple_cards")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.add_multiple_cards)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.delimeters = QtWidgets.QGroupBox(self.add_multiple_cards)
        self.delimeters.setStyleSheet("")
        self.delimeters.setObjectName("delimeters")
        self.gridLayout = QtWidgets.QGridLayout(self.delimeters)
        self.gridLayout.setObjectName("gridLayout")
        self.semicolon = QtWidgets.QRadioButton(self.delimeters)
        self.semicolon.setObjectName("semicolon")
        self.gridLayout.addWidget(self.semicolon, 1, 1, 1, 1)
        self.space = QtWidgets.QRadioButton(self.delimeters)
        self.space.setObjectName("space")
        self.gridLayout.addWidget(self.space, 1, 0, 1, 1)
        self.dot = QtWidgets.QRadioButton(self.delimeters)
        self.dot.setStyleSheet("")
        self.dot.setObjectName("dot")
        self.gridLayout.addWidget(self.dot, 0, 1, 1, 1)
        self.different = QtWidgets.QRadioButton(self.delimeters)
        self.different.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.different.setObjectName("different")
        self.gridLayout.addWidget(self.different, 2, 0, 1, 1)
        self.define_delimeters = QtWidgets.QLineEdit(self.delimeters)
        self.define_delimeters.setStyleSheet("background-color: #d3d3d3;\n"
"border-radius: 10px;\n"
"border: 1px solid #d3d3d3;\n"
"padding-left: 5px;\n"
"padding-right: 5px;")
        self.define_delimeters.setObjectName("define_delimeters")
        self.gridLayout.addWidget(self.define_delimeters, 2, 1, 1, 1)
        self.comma = QtWidgets.QRadioButton(self.delimeters)
        self.comma.setObjectName("comma")
        self.gridLayout.addWidget(self.comma, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.delimeters)
        self.add_cards_box = QtWidgets.QTextEdit(self.add_multiple_cards)
        self.add_cards_box.setStyleSheet("background-color: #d3d3d3;\n"
"border-radius: 10px;\n"
"border: 1px solid #d3d3d3;\n"
"padding-left: 5px;\n"
"padding-right: 5px;")
        self.add_cards_box.setObjectName("add_cards_box")
        self.verticalLayout_2.addWidget(self.add_cards_box)
        self.button_frame = QtWidgets.QFrame(self.add_multiple_cards)
        self.button_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.save_button_multiple = QtWidgets.QPushButton(self.button_frame)
        self.save_button_multiple.setStyleSheet("QPushButton{\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 7px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}")
        self.save_button_multiple.setObjectName("save_button_multiple")
        self.horizontalLayout.addWidget(self.save_button_multiple)
        self.cancel_button_multiple = QtWidgets.QPushButton(self.button_frame)
        self.cancel_button_multiple.setStyleSheet("QPushButton{\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;    \n"
"    background:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #7fc86b;\n"
"    border-color: #7fc86b;\n"
"    color: white;\n"
"}")
        self.cancel_button_multiple.setObjectName("cancel_button_multiple")
        self.horizontalLayout.addWidget(self.cancel_button_multiple)
        self.verticalLayout_2.addWidget(self.button_frame)
        self.tabWidget.addTab(self.add_multiple_cards, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(add_card)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(add_card)
        add_card.setTabOrder(self.tabWidget, self.card_info)
        add_card.setTabOrder(self.card_info, self.front_box)
        add_card.setTabOrder(self.front_box, self.back_box)
        add_card.setTabOrder(self.back_box, self.choose_image)
        add_card.setTabOrder(self.choose_image, self.save_button_single)
        add_card.setTabOrder(self.save_button_single, self.cancel_button_single)
        add_card.setTabOrder(self.cancel_button_single, self.comma)
        add_card.setTabOrder(self.comma, self.dot)
        add_card.setTabOrder(self.dot, self.space)
        add_card.setTabOrder(self.space, self.semicolon)
        add_card.setTabOrder(self.semicolon, self.different)
        add_card.setTabOrder(self.different, self.define_delimeters)
        add_card.setTabOrder(self.define_delimeters, self.add_cards_box)
        add_card.setTabOrder(self.add_cards_box, self.save_button_multiple)
        add_card.setTabOrder(self.save_button_multiple, self.cancel_button_multiple)

    def retranslateUi(self, add_card):
        _translate = QtCore.QCoreApplication.translate
        add_card.setWindowTitle(_translate("add_card", "Add cards to deck:"))
        self.front_label.setText(_translate("add_card", "Front"))
        self.front_box.setHtml(_translate("add_card", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p></body></html>"))
        self.back_label.setText(_translate("add_card", "Back"))
        self.back_box.setHtml(_translate("add_card", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p></body></html>"))
        self.image_label.setText(_translate("add_card", "Image"))
        self.choose_image.setText(_translate("add_card", "Choose an image..."))
        self.save_button_single.setText(_translate("add_card", "Save"))
        self.cancel_button_single.setText(_translate("add_card", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.add_single_card), _translate("add_card", "Add a single card"))
        self.delimeters.setTitle(_translate("add_card", "Delimeters"))
        self.semicolon.setText(_translate("add_card", "; (semicolon)"))
        self.space.setText(_translate("add_card", " (space)"))
        self.dot.setText(_translate("add_card", ". (dot)"))
        self.different.setText(_translate("add_card", "Different (type in the box)"))
        self.comma.setText(_translate("add_card", ", (comma)"))
        self.add_cards_box.setHtml(_translate("add_card", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><br /></p></body></html>"))
        self.add_cards_box.setPlaceholderText(_translate("add_card", "\"Type the cards in order: {id} {front} {back}} with the delimeters chosen\""))
        self.save_button_multiple.setText(_translate("add_card", "Save"))
        self.cancel_button_multiple.setText(_translate("add_card", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.add_multiple_cards), _translate("add_card", "Add multiple cards (without images)"))
