# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__add_card(object):
    def setupUi(self, _add_card):
        _add_card.setObjectName("_add_card")
        _add_card.resize(465, 340)
        _add_card.setWindowOpacity(1.0)
        self.verticalLayout = QtWidgets.QVBoxLayout(_add_card)
        self.verticalLayout.setObjectName("verticalLayout")
        self._add_card_form = QtWidgets.QFrame(_add_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._add_card_form.sizePolicy().hasHeightForWidth())
        self._add_card_form.setSizePolicy(sizePolicy)
        self._add_card_form.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._add_card_form.setFrameShadow(QtWidgets.QFrame.Raised)
        self._add_card_form.setObjectName("_add_card_form")
        self.formLayout = QtWidgets.QFormLayout(self._add_card_form)
        self.formLayout.setObjectName("formLayout")
        self._front_label = QtWidgets.QLabel(self._add_card_form)
        self._front_label.setObjectName("_front_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self._front_label)
        self._front_box = QtWidgets.QTextEdit(self._add_card_form)
        self._front_box.setMinimumSize(QtCore.QSize(0, 100))
        self._front_box.setObjectName("_front_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self._front_box)
        self._back_label = QtWidgets.QLabel(self._add_card_form)
        self._back_label.setObjectName("_back_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self._back_label)
        self._back_box = QtWidgets.QTextEdit(self._add_card_form)
        self._back_box.setMinimumSize(QtCore.QSize(0, 100))
        self._back_box.setObjectName("_back_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self._back_box)
        self._img_label = QtWidgets.QLabel(self._add_card_form)
        self._img_label.setObjectName("_img_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self._img_label)
        self._choose_image = QtWidgets.QPushButton(self._add_card_form)
        self._choose_image.setObjectName("_choose_image")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self._choose_image)
        self.verticalLayout.addWidget(self._add_card_form)
        self._img = QtWidgets.QLabel(_add_card)
        self._img.setText("")
        self._img.setAlignment(QtCore.Qt.AlignCenter)
        self._img.setObjectName("_img")
        self.verticalLayout.addWidget(self._img)
        self._button_frame = QtWidgets.QFrame(_add_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._button_frame.sizePolicy().hasHeightForWidth())
        self._button_frame.setSizePolicy(sizePolicy)
        self._button_frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self._button_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._button_frame.setObjectName("_button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._button_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._cancel_button = QtWidgets.QPushButton(self._button_frame)
        self._cancel_button.setStyleSheet("QPushButton{\n"
"    background-color: #d3d3d3;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #a1a1a1;\n"
"    color: white;\n"
"}")
        self._cancel_button.setObjectName("_cancel_button")
        self.horizontalLayout.addWidget(self._cancel_button)
        self._save_button = QtWidgets.QPushButton(self._button_frame)
        self._save_button.setStyleSheet("QPushButton{\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"    color: white;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}")
        self._save_button.setObjectName("_save_button")
        self.horizontalLayout.addWidget(self._save_button)
        self.verticalLayout.addWidget(self._button_frame)

        self.retranslateUi(_add_card)
        QtCore.QMetaObject.connectSlotsByName(_add_card)

    def retranslateUi(self, _add_card):
        _translate = QtCore.QCoreApplication.translate
        _add_card.setWindowTitle(_translate("_add_card", "Add new card to deck: "))
        self._front_label.setText(_translate("_add_card", "Front"))
        self._back_label.setText(_translate("_add_card", "Back"))
        self._img_label.setText(_translate("_add_card", "Image"))
        self._choose_image.setText(_translate("_add_card", "Choose an image..."))
        self._cancel_button.setText(_translate("_add_card", "Cancel"))
        self._save_button.setText(_translate("_add_card", "Save"))
