# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/browse_deck.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__browse_deck(object):
    def setupUi(self, _browse_deck):
        _browse_deck.setObjectName("_browse_deck")
        _browse_deck.resize(679, 503)
        _browse_deck.setMinimumSize(QtCore.QSize(600, 400))
        _browse_deck.setStyleSheet("/*QWidget#_browse_deck, QWidget#_all_decks_area{\n"
"    background: white;\n"
"}*/\n"
"\n"
"QScrollBar:vertical {\n"
"       border: 0;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(_browse_deck)
        self.verticalLayout.setObjectName("verticalLayout")
        self._all_deck_label = QtWidgets.QLabel(_browse_deck)
        font = QtGui.QFont()
        font.setPointSize(16)
        self._all_deck_label.setFont(font)
        self._all_deck_label.setObjectName("_all_deck_label")
        self.verticalLayout.addWidget(self._all_deck_label)
        self._button_frame = QtWidgets.QFrame(_browse_deck)
        self._button_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._button_frame.setObjectName("_button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._button_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._add_deck = QtWidgets.QPushButton(self._button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._add_deck.sizePolicy().hasHeightForWidth())
        self._add_deck.setSizePolicy(sizePolicy)
        self._add_deck.setMinimumSize(QtCore.QSize(100, 0))
        self._add_deck.setStyleSheet("QPushButton{\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}\n"
"")
        self._add_deck.setObjectName("_add_deck")
        self.horizontalLayout.addWidget(self._add_deck)
        self.verticalLayout.addWidget(self._button_frame)
        self.scrollArea = QtWidgets.QScrollArea(_browse_deck)
        self.scrollArea.setMinimumSize(QtCore.QSize(550, 0))
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"       border: 0;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"       border: 0;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self._all_decks_area = QtWidgets.QWidget()
        self._all_decks_area.setGeometry(QtCore.QRect(0, 0, 655, 542))
        self._all_decks_area.setMinimumSize(QtCore.QSize(600, 0))
        self._all_decks_area.setObjectName("_all_decks_area")
        self.gridLayout = QtWidgets.QGridLayout(self._all_decks_area)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self._all_decks_area)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 100))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self._all_decks_area)
        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 100))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self._all_decks_area)
        self.pushButton_4.setMinimumSize(QtCore.QSize(200, 100))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self._all_decks_area)
        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self._all_decks_area)
        self.pushButton_5.setMinimumSize(QtCore.QSize(200, 100))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 0, 1, 1)
        self.scrollArea.setWidget(self._all_decks_area)
        self.verticalLayout.addWidget(self.scrollArea)
        self._number_of_decks = QtWidgets.QLabel(_browse_deck)
        self._number_of_decks.setObjectName("_number_of_decks")
        self.verticalLayout.addWidget(self._number_of_decks)

        self.retranslateUi(_browse_deck)
        QtCore.QMetaObject.connectSlotsByName(_browse_deck)

    def retranslateUi(self, _browse_deck):
        _translate = QtCore.QCoreApplication.translate
        _browse_deck.setWindowTitle(_translate("_browse_deck", "All decks"))
        self._all_deck_label.setText(_translate("_browse_deck", "All decks"))
        self._add_deck.setText(_translate("_browse_deck", "Add deck"))
        self.pushButton.setText(_translate("_browse_deck", "PushButton"))
        self.pushButton_3.setText(_translate("_browse_deck", "PushButton"))
        self.pushButton_4.setText(_translate("_browse_deck", "PushButton"))
        self.pushButton_2.setText(_translate("_browse_deck", "PushButton"))
        self.pushButton_5.setText(_translate("_browse_deck", "PushButton"))
        self._number_of_decks.setText(_translate("_browse_deck", "0 decks"))
