# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/browse_deck.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__browse_deck(object):
    def setupUi(self, _browse_deck):
        _browse_deck.setObjectName("_browse_deck")
        _browse_deck.resize(675, 530)
        _browse_deck.setMinimumSize(QtCore.QSize(650, 530))
        _browse_deck.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(_browse_deck)
        self.verticalLayout.setObjectName("verticalLayout")
        self._add_deck_label = QtWidgets.QLabel(_browse_deck)
        font = QtGui.QFont()
        font.setPointSize(16)
        self._add_deck_label.setFont(font)
        self._add_deck_label.setObjectName("_add_deck_label")
        self.verticalLayout.addWidget(self._add_deck_label)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.button_frame = QtWidgets.QFrame(_browse_deck)
        self.button_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.button_frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self._more_funcs = QtWidgets.QToolButton(self.button_frame)
        self._more_funcs.setStyleSheet("QToolButton{\n"
"    background: white;\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    background-color: #7fc86b;\n"
"    border-color: #7fc86b;\n"
"    color: white;\n"
"}\n"
"\n"
"QToolButton:menu-indicator{\n"
"    width: 0px;\n"
"}")
        self._more_funcs.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self._more_funcs.setObjectName("_more_funcs")
        self.horizontalLayout_3.addWidget(self._more_funcs)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self._add_deck = QtWidgets.QPushButton(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._add_deck.sizePolicy().hasHeightForWidth())
        self._add_deck.setSizePolicy(sizePolicy)
        self._add_deck.setMinimumSize(QtCore.QSize(0, 30))
        self._add_deck.setStyleSheet("QPushButton{\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}")
        self._add_deck.setObjectName("_add_deck")
        self.horizontalLayout_3.addWidget(self._add_deck)
        self.verticalLayout.addWidget(self.button_frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self._all_decks_area = QtWidgets.QScrollArea(_browse_deck)
        self._all_decks_area.setMinimumSize(QtCore.QSize(0, 320))
        self._all_decks_area.setStyleSheet("/*Vertical*/\n"
"QScrollBar:vertical {\n"
"       border: 0;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"/*Horizontal*/\n"
"QScrollBar:horizontal {\n"
"       border: 0;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}")
        self._all_decks_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._all_decks_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self._all_decks_area.setMidLineWidth(0)
        self._all_decks_area.setWidgetResizable(True)
        self._all_decks_area.setObjectName("_all_decks_area")
        self._decks_widget = QtWidgets.QWidget()
        self._decks_widget.setGeometry(QtCore.QRect(0, 0, 663, 330))
        self._decks_widget.setStyleSheet("")
        self._decks_widget.setObjectName("_decks_widget")
        self.gridLayout = QtWidgets.QGridLayout(self._decks_widget)
        self.gridLayout.setObjectName("gridLayout")
        self._all_decks_area.setWidget(self._decks_widget)
        self.verticalLayout.addWidget(self._all_decks_area)
        self._number_of_decks = QtWidgets.QLabel(_browse_deck)
        self._number_of_decks.setObjectName("_number_of_decks")
        self.verticalLayout.addWidget(self._number_of_decks)

        self.retranslateUi(_browse_deck)
        QtCore.QMetaObject.connectSlotsByName(_browse_deck)

    def retranslateUi(self, _browse_deck):
        _translate = QtCore.QCoreApplication.translate
        _browse_deck.setWindowTitle(_translate("_browse_deck", "Form"))
        self._add_deck_label.setText(_translate("_browse_deck", "All decks"))
        self._more_funcs.setText(_translate("_browse_deck", "..."))
        self._add_deck.setText(_translate("_browse_deck", "Add deck"))
        self._number_of_decks.setText(_translate("_browse_deck", "0 decks"))
