# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/edit_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__edit_card(object):
    def setupUi(self, _edit_card):
        _edit_card.setObjectName("_edit_card")
        _edit_card.resize(400, 311)
        _edit_card.setStyleSheet("QDialog#_edit_card{\n"
"    background: white;\n"
"}")
        self.formLayout = QtWidgets.QFormLayout(_edit_card)
        self.formLayout.setObjectName("formLayout")
        self._front_label = QtWidgets.QLabel(_edit_card)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._front_label.sizePolicy().hasHeightForWidth())
        self._front_label.setSizePolicy(sizePolicy)
        self._front_label.setObjectName("_front_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self._front_label)
        self._front = QtWidgets.QLabel(_edit_card)
        self._front.setObjectName("_front")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self._front)
        self._back_label = QtWidgets.QLabel(_edit_card)
        self._back_label.setObjectName("_back_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self._back_label)
        self._back_box = QtWidgets.QTextEdit(_edit_card)
        self._back_box.setStyleSheet("border-radius: 10px;\n"
"background-color: #dedede;\n"
"padding-left: 5px;\n"
"padding-right: 5px;")
        self._back_box.setObjectName("_back_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self._back_box)
        self._img_label = QtWidgets.QLabel(_edit_card)
        self._img_label.setObjectName("_img_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self._img_label)
        self._img_preview = QtWidgets.QLabel(_edit_card)
        self._img_preview.setObjectName("_img_preview")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self._img_preview)
        self._img_button = QtWidgets.QToolButton(_edit_card)
        self._img_button.setStyleSheet("QToolButton{\n"
"    /*background: #d3d3d3;*/\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    background-color: #7fc86b;\n"
"    border-color: #7fc86b;\n"
"    color: white;\n"
"}")
        self._img_button.setObjectName("_img_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self._img_button)
        self.button_frame = QtWidgets.QFrame(_edit_card)
        self.button_frame.setStyleSheet("QPushButton{\n"
"    border: 0px;\n"
"    background: #d3d3d3;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: #a1a1a1;\n"
"    color:white;\n"
"}")
        self.button_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self._save_button = QtWidgets.QPushButton(self.button_frame)
        self._save_button.setStyleSheet("QPushButton{\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}")
        self._save_button.setObjectName("_save_button")
        self.horizontalLayout.addWidget(self._save_button)
        self._cancel_button = QtWidgets.QPushButton(self.button_frame)
        self._cancel_button.setObjectName("_cancel_button")
        self.horizontalLayout.addWidget(self._cancel_button)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.button_frame)

        self.retranslateUi(_edit_card)
        QtCore.QMetaObject.connectSlotsByName(_edit_card)

    def retranslateUi(self, _edit_card):
        _translate = QtCore.QCoreApplication.translate
        _edit_card.setWindowTitle(_translate("_edit_card", "Edit card: "))
        self._front_label.setText(_translate("_edit_card", "Card"))
        self._front.setText(_translate("_edit_card", "{{Front}}"))
        self._back_label.setText(_translate("_edit_card", "Back"))
        self._img_label.setText(_translate("_edit_card", "Image"))
        self._img_preview.setText(_translate("_edit_card", "{{Preview}}"))
        self._img_button.setText(_translate("_edit_card", "Change Image"))
        self._save_button.setText(_translate("_edit_card", "Save"))
        self._cancel_button.setText(_translate("_edit_card", "Cancel"))
