# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/edit_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__edit_card(object):
    def setupUi(self, _edit_card):
        _edit_card.setObjectName("_edit_card")
        _edit_card.resize(427, 454)
        _edit_card.setStyleSheet("background: white;")
        self.verticalLayout = QtWidgets.QVBoxLayout(_edit_card)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(_edit_card)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self._front_label = QtWidgets.QLabel(self.frame)
        self._front_label.setMinimumSize(QtCore.QSize(0, 20))
        self._front_label.setObjectName("_front_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self._front_label)
        self._front = QtWidgets.QLabel(self.frame)
        self._front.setObjectName("_front")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self._front)
        self._back_label = QtWidgets.QLabel(self.frame)
        self._back_label.setMinimumSize(QtCore.QSize(0, 100))
        self._back_label.setObjectName("_back_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self._back_label)
        self._back_box = QtWidgets.QTextEdit(self.frame)
        self._back_box.setMinimumSize(QtCore.QSize(0, 150))
        self._back_box.setStyleSheet("border-radius: 10px;\n"
"background-color: #dedede;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"")
        self._back_box.setObjectName("_back_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self._back_box)
        self._img_label = QtWidgets.QLabel(self.frame)
        self._img_label.setMinimumSize(QtCore.QSize(0, 30))
        self._img_label.setObjectName("_img_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self._img_label)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"    border: 0;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    height: 0px;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 357, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_2 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_2.setObjectName("formLayout_2")
        self._img_preview = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self._img_preview.setMinimumSize(QtCore.QSize(0, 0))
        self._img_preview.setObjectName("_img_preview")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self._img_preview)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.scrollArea)
        self._img_button = QtWidgets.QToolButton(self.frame)
        self._img_button.setStyleSheet("QToolButton{\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    background-color: #7fc86b;\n"
"    border-color: #7fc86b;\n"
"    color: white;\n"
"}")
        self._img_button.setObjectName("_img_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self._img_button)
        self.verticalLayout.addWidget(self.frame)
        self._button_frame = QtWidgets.QFrame(_edit_card)
        self._button_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._button_frame.setObjectName("_button_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self._button_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self._save_button = QtWidgets.QPushButton(self._button_frame)
        self._save_button.setStyleSheet("QPushButton{\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 7px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}")
        self._save_button.setObjectName("_save_button")
        self.horizontalLayout_2.addWidget(self._save_button)
        self._cancel_button = QtWidgets.QPushButton(self._button_frame)
        self._cancel_button.setStyleSheet("QPushButton{\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #7fc86b;\n"
"    border-color: #7fc86b;\n"
"    color: white;\n"
"}")
        self._cancel_button.setObjectName("_cancel_button")
        self.horizontalLayout_2.addWidget(self._cancel_button)
        self.verticalLayout.addWidget(self._button_frame)

        self.retranslateUi(_edit_card)
        QtCore.QMetaObject.connectSlotsByName(_edit_card)

    def retranslateUi(self, _edit_card):
        _translate = QtCore.QCoreApplication.translate
        _edit_card.setWindowTitle(_translate("_edit_card", "Edit card: "))
        self._front_label.setText(_translate("_edit_card", "Front"))
        self._front.setText(_translate("_edit_card", "{{Front}}"))
        self._back_label.setText(_translate("_edit_card", "Back"))
        self._img_label.setText(_translate("_edit_card", "Image"))
        self._img_preview.setText(_translate("_edit_card", "{{Preview}}"))
        self._img_button.setText(_translate("_edit_card", "Change "))
        self._save_button.setText(_translate("_edit_card", "Save"))
        self._cancel_button.setText(_translate("_edit_card", "Cancel"))
