# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/game_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__game_mode(object):
    def setupUi(self, _game_mode):
        _game_mode.setObjectName("_game_mode")
        _game_mode.resize(853, 541)
        _game_mode.setStyleSheet("QWidget{\n"
"    background: white;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(_game_mode)
        self.gridLayout.setObjectName("gridLayout")
        self._score_frame = QtWidgets.QFrame(_game_mode)
        self._score_frame.setMinimumSize(QtCore.QSize(200, 0))
        self._score_frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self._score_frame.setStyleSheet("border-radius: 5px")
        self._score_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._score_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._score_frame.setObjectName("_score_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self._score_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self._score_label = QtWidgets.QLabel(self._score_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._score_label.sizePolicy().hasHeightForWidth())
        self._score_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self._score_label.setFont(font)
        self._score_label.setAlignment(QtCore.Qt.AlignCenter)
        self._score_label.setObjectName("_score_label")
        self.verticalLayout.addWidget(self._score_label)
        self._score = QtWidgets.QLabel(self._score_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._score.sizePolicy().hasHeightForWidth())
        self._score.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self._score.setFont(font)
        self._score.setStyleSheet("margin-bottom: 30px;\n"
"margin-top: 30px;\n"
"color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );")
        self._score.setAlignment(QtCore.Qt.AlignCenter)
        self._score.setObjectName("_score")
        self.verticalLayout.addWidget(self._score)
        self._revise_label = QtWidgets.QLabel(self._score_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._revise_label.sizePolicy().hasHeightForWidth())
        self._revise_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self._revise_label.setFont(font)
        self._revise_label.setObjectName("_revise_label")
        self.verticalLayout.addWidget(self._revise_label)
        self._revised_frame = QtWidgets.QScrollArea(self._score_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._revised_frame.sizePolicy().hasHeightForWidth())
        self._revised_frame.setSizePolicy(sizePolicy)
        self._revised_frame.setStyleSheet("QWidget{\n"
"    background: white;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: 0;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: 0;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}")
        self._revised_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._revised_frame.setWidgetResizable(True)
        self._revised_frame.setObjectName("_revised_frame")
        self.revised_widget = QtWidgets.QWidget()
        self.revised_widget.setGeometry(QtCore.QRect(0, 0, 188, 349))
        self.revised_widget.setObjectName("revised_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.revised_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self._revised_frame.setWidget(self.revised_widget)
        self.verticalLayout.addWidget(self._revised_frame)
        self.gridLayout.addWidget(self._score_frame, 0, 2, 5, 1)
        self.header_frame = QtWidgets.QFrame(_game_mode)
        self.header_frame.setStyleSheet("border-radius: 5px;")
        self.header_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._back = QtWidgets.QPushButton(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._back.sizePolicy().hasHeightForWidth())
        self._back.setSizePolicy(sizePolicy)
        self._back.setStyleSheet("QPushButton{\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;    \n"
"    background:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #7fc86b;\n"
"    border-color: #7fc86b;\n"
"    color: white;\n"
"}")
        self._back.setObjectName("_back")
        self.horizontalLayout_2.addWidget(self._back)
        self._game_progress = QtWidgets.QProgressBar(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._game_progress.sizePolicy().hasHeightForWidth())
        self._game_progress.setSizePolicy(sizePolicy)
        self._game_progress.setMinimumSize(QtCore.QSize(0, 0))
        self._game_progress.setMaximumSize(QtCore.QSize(16777215, 10))
        self._game_progress.setStyleSheet("QProgressBar{\n"
"    border: 0px;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(227, 227, 227);\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border: 0px;\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"  border-radius: 5px;\n"
"}")
        self._game_progress.setProperty("value", 24)
        self._game_progress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self._game_progress.setTextVisible(False)
        self._game_progress.setOrientation(QtCore.Qt.Horizontal)
        self._game_progress.setInvertedAppearance(False)
        self._game_progress.setFormat("")
        self._game_progress.setObjectName("_game_progress")
        self.horizontalLayout_2.addWidget(self._game_progress)
        self.gridLayout.addWidget(self.header_frame, 0, 1, 1, 1)
        self._question_widget = QtWidgets.QStackedWidget(_game_mode)
        self._question_widget.setStyleSheet("QPushButton{\n"
"    background: #d3d3d3;\n"
"    border-radius: 5px;\n"
"    padding: 20px 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(157, 157, 157);\n"
"    color: white;\n"
"}")
        self._question_widget.setObjectName("_question_widget")
        self._box_filling = QtWidgets.QWidget()
        self._box_filling.setObjectName("_box_filling")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self._box_filling)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.typing_label = QtWidgets.QLabel(self._box_filling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typing_label.sizePolicy().hasHeightForWidth())
        self.typing_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.typing_label.setFont(font)
        self.typing_label.setStyleSheet("color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );")
        self.typing_label.setAlignment(QtCore.Qt.AlignCenter)
        self.typing_label.setObjectName("typing_label")
        self.verticalLayout_2.addWidget(self.typing_label)
        self._question_frame = QtWidgets.QFrame(self._box_filling)
        self._question_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._question_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._question_frame.setObjectName("_question_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._question_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.question_img = QtWidgets.QLabel(self._question_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_img.sizePolicy().hasHeightForWidth())
        self.question_img.setSizePolicy(sizePolicy)
        self.question_img.setMaximumSize(QtCore.QSize(200, 100))
        self.question_img.setText("")
        self.question_img.setPixmap(QtGui.QPixmap("ui/../../../Downloads/dien-bien-bat-ngo-khi-ta-ga-trong-f5f141.jpg"))
        self.question_img.setScaledContents(True)
        self.question_img.setObjectName("question_img")
        self.horizontalLayout.addWidget(self.question_img)
        self.question_label = QtWidgets.QLabel(self._question_frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.question_label.setFont(font)
        self.question_label.setWordWrap(True)
        self.question_label.setOpenExternalLinks(False)
        self.question_label.setObjectName("question_label")
        self.horizontalLayout.addWidget(self.question_label)
        self.verticalLayout_2.addWidget(self._question_frame)
        self._answer_box = QtWidgets.QTextEdit(self._box_filling)
        self._answer_box.setStyleSheet("background-color: #d3d3d3;\n"
"padding: 5px;\n"
"border-radius: 5px;")
        self._answer_box.setObjectName("_answer_box")
        self.verticalLayout_2.addWidget(self._answer_box)
        self._submit_frame = QtWidgets.QFrame(self._box_filling)
        self._submit_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._submit_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._submit_frame.setObjectName("_submit_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self._submit_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self._submit = QtWidgets.QPushButton(self._submit_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._submit.sizePolicy().hasHeightForWidth())
        self._submit.setSizePolicy(sizePolicy)
        self._submit.setStyleSheet("QPushButton{\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}")
        self._submit.setObjectName("_submit")
        self.horizontalLayout_3.addWidget(self._submit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self._submit_frame)
        self._question_widget.addWidget(self._box_filling)
        self._multiple = QtWidgets.QWidget()
        self._multiple.setObjectName("_multiple")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self._multiple)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.typing_label_2 = QtWidgets.QLabel(self._multiple)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typing_label_2.sizePolicy().hasHeightForWidth())
        self.typing_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.typing_label_2.setFont(font)
        self.typing_label_2.setStyleSheet("color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );")
        self.typing_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.typing_label_2.setObjectName("typing_label_2")
        self.verticalLayout_3.addWidget(self.typing_label_2)
        self._question_frame_2 = QtWidgets.QFrame(self._multiple)
        self._question_frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._question_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self._question_frame_2.setObjectName("_question_frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self._question_frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.question_img_2 = QtWidgets.QLabel(self._question_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_img_2.sizePolicy().hasHeightForWidth())
        self.question_img_2.setSizePolicy(sizePolicy)
        self.question_img_2.setMaximumSize(QtCore.QSize(200, 100))
        self.question_img_2.setText("")
        self.question_img_2.setPixmap(QtGui.QPixmap("ui/../../../Downloads/dien-bien-bat-ngo-khi-ta-ga-trong-f5f141.jpg"))
        self.question_img_2.setScaledContents(True)
        self.question_img_2.setObjectName("question_img_2")
        self.horizontalLayout_4.addWidget(self.question_img_2)
        self.question_label_2 = QtWidgets.QLabel(self._question_frame_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.question_label_2.setFont(font)
        self.question_label_2.setWordWrap(True)
        self.question_label_2.setOpenExternalLinks(False)
        self.question_label_2.setObjectName("question_label_2")
        self.horizontalLayout_4.addWidget(self.question_label_2)
        self.verticalLayout_3.addWidget(self._question_frame_2)
        self.answer_frame = QtWidgets.QFrame(self._multiple)
        self.answer_frame.setStyleSheet("QPushButton{\n"
"    background: #d3d3d3;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(157, 157, 157);\n"
"    color: white;\n"
"}")
        self.answer_frame.setObjectName("answer_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.answer_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_D = QtWidgets.QPushButton(self.answer_frame)
        self.button_D.setObjectName("button_D")
        self.gridLayout_2.addWidget(self.button_D, 1, 1, 1, 1)
        self.button_A = QtWidgets.QPushButton(self.answer_frame)
        self.button_A.setCheckable(False)
        self.button_A.setAutoDefault(False)
        self.button_A.setDefault(False)
        self.button_A.setFlat(False)
        self.button_A.setObjectName("button_A")
        self.gridLayout_2.addWidget(self.button_A, 0, 0, 1, 1)
        self.button_B = QtWidgets.QPushButton(self.answer_frame)
        self.button_B.setObjectName("button_B")
        self.gridLayout_2.addWidget(self.button_B, 0, 1, 1, 1)
        self.button_C = QtWidgets.QPushButton(self.answer_frame)
        self.button_C.setObjectName("button_C")
        self.gridLayout_2.addWidget(self.button_C, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.answer_frame)
        self._question_widget.addWidget(self._multiple)
        self.gridLayout.addWidget(self._question_widget, 1, 1, 1, 1)

        self.retranslateUi(_game_mode)
        self._question_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(_game_mode)

    def retranslateUi(self, _game_mode):
        _translate = QtCore.QCoreApplication.translate
        _game_mode.setWindowTitle(_translate("_game_mode", "Game mode for deck: "))
        self._score_label.setText(_translate("_game_mode", "Your score:"))
        self._score.setText(_translate("_game_mode", "0"))
        self._revise_label.setText(_translate("_game_mode", "Revised"))
        self._back.setText(_translate("_game_mode", "Back"))
        self.typing_label.setText(_translate("_game_mode", "Type the right answer"))
        self.question_label.setText(_translate("_game_mode", "Question"))
        self._submit.setText(_translate("_game_mode", "Submit"))
        self.typing_label_2.setText(_translate("_game_mode", "Choose the right answer"))
        self.question_label_2.setText(_translate("_game_mode", "Question"))
        self.button_D.setText(_translate("_game_mode", "D. PushButton"))
        self.button_A.setText(_translate("_game_mode", "A. PushButton"))
        self.button_B.setText(_translate("_game_mode", "B. PushButton"))
        self.button_C.setText(_translate("_game_mode", "C. PushButton"))
