# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/game_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__game_mode(object):
    def setupUi(self, _game_mode):
        _game_mode.setObjectName("_game_mode")
        _game_mode.resize(845, 541)
        self.gridLayout = QtWidgets.QGridLayout(_game_mode)
        self.gridLayout.setObjectName("gridLayout")
        self._questions_frame = QtWidgets.QStackedWidget(_game_mode)
        self._questions_frame.setStyleSheet("QWidget{\n"
"    background-color: white; \n"
"    border-radius: 10px;\n"
"}")
        self._questions_frame.setObjectName("_questions_frame")
        self._written = QtWidgets.QWidget()
        self._written.setObjectName("_written")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self._written)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self._title_written = QtWidgets.QLabel(self._written)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._title_written.sizePolicy().hasHeightForWidth())
        self._title_written.setSizePolicy(sizePolicy)
        self._title_written.setMinimumSize(QtCore.QSize(0, 50))
        self._title_written.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self._title_written.setFont(font)
        self._title_written.setStyleSheet("color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );")
        self._title_written.setAlignment(QtCore.Qt.AlignCenter)
        self._title_written.setObjectName("_title_written")
        self.verticalLayout_3.addWidget(self._title_written)
        self._back_frame = QtWidgets.QFrame(self._written)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._back_frame.sizePolicy().hasHeightForWidth())
        self._back_frame.setSizePolicy(sizePolicy)
        self._back_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._back_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._back_frame.setObjectName("_back_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._back_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._img_written = QtWidgets.QLabel(self._back_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._img_written.sizePolicy().hasHeightForWidth())
        self._img_written.setSizePolicy(sizePolicy)
        self._img_written.setMinimumSize(QtCore.QSize(100, 100))
        self._img_written.setMaximumSize(QtCore.QSize(100, 100))
        self._img_written.setText("")
        self._img_written.setPixmap(QtGui.QPixmap("ui/../../../Pictures/plot_1.png"))
        self._img_written.setScaledContents(True)
        self._img_written.setObjectName("_img_written")
        self.horizontalLayout.addWidget(self._img_written)
        self._back_written = QtWidgets.QLabel(self._back_frame)
        self._back_written.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self._back_written.setFont(font)
        self._back_written.setStyleSheet("padding-left: 10px;\n"
"padding-right: 10px;")
        self._back_written.setObjectName("_back_written")
        self.horizontalLayout.addWidget(self._back_written)
        self.verticalLayout_3.addWidget(self._back_frame)
        self._answer_box = QtWidgets.QLineEdit(self._written)
        self._answer_box.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self._answer_box.setFont(font)
        self._answer_box.setStyleSheet("background-color: #d3d3d3;\n"
"padding: 5px;")
        self._answer_box.setObjectName("_answer_box")
        self.verticalLayout_3.addWidget(self._answer_box)
        self._submit_frame = QtWidgets.QFrame(self._written)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._submit_frame.sizePolicy().hasHeightForWidth())
        self._submit_frame.setSizePolicy(sizePolicy)
        self._submit_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._submit_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._submit_frame.setObjectName("_submit_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self._submit_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self._submit_button = QtWidgets.QPushButton(self._submit_frame)
        self._submit_button.setMinimumSize(QtCore.QSize(0, 40))
        self._submit_button.setMaximumSize(QtCore.QSize(500, 40))
        self._submit_button.setStyleSheet("QPushButton{\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"    color: white;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}\n"
"")
        self._submit_button.setObjectName("_submit_button")
        self.horizontalLayout_3.addWidget(self._submit_button)
        self.verticalLayout_3.addWidget(self._submit_frame)
        self._questions_frame.addWidget(self._written)
        self._multiple = QtWidgets.QWidget()
        self._multiple.setObjectName("_multiple")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self._multiple)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self._title_multiple = QtWidgets.QLabel(self._multiple)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._title_multiple.sizePolicy().hasHeightForWidth())
        self._title_multiple.setSizePolicy(sizePolicy)
        self._title_multiple.setMinimumSize(QtCore.QSize(0, 50))
        self._title_multiple.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self._title_multiple.setFont(font)
        self._title_multiple.setStyleSheet("color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );")
        self._title_multiple.setAlignment(QtCore.Qt.AlignCenter)
        self._title_multiple.setObjectName("_title_multiple")
        self.verticalLayout_4.addWidget(self._title_multiple)
        self._back_frame_2 = QtWidgets.QFrame(self._multiple)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._back_frame_2.sizePolicy().hasHeightForWidth())
        self._back_frame_2.setSizePolicy(sizePolicy)
        self._back_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._back_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self._back_frame_2.setObjectName("_back_frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self._back_frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._img_multiple = QtWidgets.QLabel(self._back_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._img_multiple.sizePolicy().hasHeightForWidth())
        self._img_multiple.setSizePolicy(sizePolicy)
        self._img_multiple.setMinimumSize(QtCore.QSize(100, 100))
        self._img_multiple.setMaximumSize(QtCore.QSize(100, 100))
        self._img_multiple.setText("")
        self._img_multiple.setPixmap(QtGui.QPixmap("ui/../../../Pictures/plot_1.png"))
        self._img_multiple.setScaledContents(True)
        self._img_multiple.setObjectName("_img_multiple")
        self.horizontalLayout_2.addWidget(self._img_multiple)
        self._back_multiple = QtWidgets.QLabel(self._back_frame_2)
        self._back_multiple.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self._back_multiple.setFont(font)
        self._back_multiple.setStyleSheet("padding-left: 10px;\n"
"padding-right: 10px;")
        self._back_multiple.setObjectName("_back_multiple")
        self.horizontalLayout_2.addWidget(self._back_multiple)
        self.verticalLayout_4.addWidget(self._back_frame_2)
        self._button_frame = QtWidgets.QFrame(self._multiple)
        self._button_frame.setStyleSheet("QPushButton{\n"
"    background: #d3d3d3;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgb(157, 157, 157);\n"
"    color: white;\n"
"}")
        self._button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._button_frame.setObjectName("_button_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self._button_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._button_D = QtWidgets.QPushButton(self._button_frame)
        self._button_D.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self._button_D.setFont(font)
        self._button_D.setObjectName("_button_D")
        self.gridLayout_2.addWidget(self._button_D, 2, 1, 1, 1)
        self._button_A = QtWidgets.QPushButton(self._button_frame)
        self._button_A.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self._button_A.setFont(font)
        self._button_A.setFlat(True)
        self._button_A.setObjectName("_button_A")
        self.gridLayout_2.addWidget(self._button_A, 1, 0, 1, 1)
        self._button_C = QtWidgets.QPushButton(self._button_frame)
        self._button_C.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self._button_C.setFont(font)
        self._button_C.setObjectName("_button_C")
        self.gridLayout_2.addWidget(self._button_C, 2, 0, 1, 1)
        self._button_B = QtWidgets.QPushButton(self._button_frame)
        self._button_B.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self._button_B.setFont(font)
        self._button_B.setObjectName("_button_B")
        self.gridLayout_2.addWidget(self._button_B, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self._button_frame)
        self._questions_frame.addWidget(self._multiple)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self._questions_frame.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self._questions_frame.addWidget(self.page_4)
        self.gridLayout.addWidget(self._questions_frame, 1, 2, 1, 1)
        self._game_progress = QtWidgets.QProgressBar(_game_mode)
        self._game_progress.setStyleSheet("QProgressBar{\n"
"    height: 4px;\n"
"    border: 0px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border: 0px;\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );;\n"
"}")
        self._game_progress.setProperty("value", 24)
        self._game_progress.setAlignment(QtCore.Qt.AlignCenter)
        self._game_progress.setObjectName("_game_progress")
        self.gridLayout.addWidget(self._game_progress, 0, 2, 1, 1)
        self._score_frame = QtWidgets.QFrame(_game_mode)
        self._score_frame.setMinimumSize(QtCore.QSize(200, 0))
        self._score_frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self._score_frame.setStyleSheet("QFrame{\n"
"    background-color: white; \n"
"    border-radius: 10px;\n"
"}")
        self._score_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._score_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._score_frame.setObjectName("_score_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self._score_frame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self._score_label = QtWidgets.QLabel(self._score_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._score_label.sizePolicy().hasHeightForWidth())
        self._score_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self._score_label.setFont(font)
        self._score_label.setAlignment(QtCore.Qt.AlignCenter)
        self._score_label.setObjectName("_score_label")
        self.verticalLayout.addWidget(self._score_label)
        self._score = QtWidgets.QLabel(self._score_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._score.sizePolicy().hasHeightForWidth())
        self._score.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self._score.setFont(font)
        self._score.setStyleSheet("margin-bottom: 30px;\n"
"margin-top: 30px;\n"
"color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );")
        self._score.setAlignment(QtCore.Qt.AlignCenter)
        self._score.setObjectName("_score")
        self.verticalLayout.addWidget(self._score)
        self._revised_label = QtWidgets.QLabel(self._score_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._revised_label.sizePolicy().hasHeightForWidth())
        self._revised_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self._revised_label.setFont(font)
        self._revised_label.setObjectName("_revised_label")
        self.verticalLayout.addWidget(self._revised_label)
        self._revised_frame = QtWidgets.QScrollArea(self._score_frame)
        self._revised_frame.setMinimumSize(QtCore.QSize(0, 50))
        self._revised_frame.setStyleSheet("QWidget{\n"
"    background: white;\n"
"}\n"
"QScrollBar:vertical {\n"
"       border: 0;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"       border: 0;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"")
        self._revised_frame.setWidgetResizable(True)
        self._revised_frame.setObjectName("_revised_frame")
        self._revised_widget = QtWidgets.QWidget()
        self._revised_widget.setGeometry(QtCore.QRect(0, 0, 232, 352))
        self._revised_widget.setObjectName("_revised_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self._revised_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self._revised_frame.setWidget(self._revised_widget)
        self.verticalLayout.addWidget(self._revised_frame)
        self.gridLayout.addWidget(self._score_frame, 0, 3, 4, 1)

        self.retranslateUi(_game_mode)
        self._questions_frame.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(_game_mode)

    def retranslateUi(self, _game_mode):
        _translate = QtCore.QCoreApplication.translate
        _game_mode.setWindowTitle(_translate("_game_mode", "Form"))
        self._title_written.setText(_translate("_game_mode", "Type the answer"))
        self._back_written.setText(_translate("_game_mode", "biểu đồ"))
        self._submit_button.setText(_translate("_game_mode", "Submit"))
        self._title_multiple.setText(_translate("_game_mode", "Choose the right answer"))
        self._back_multiple.setText(_translate("_game_mode", "biểu đồ"))
        self._button_D.setText(_translate("_game_mode", "PushButton"))
        self._button_A.setText(_translate("_game_mode", "PushButton"))
        self._button_C.setText(_translate("_game_mode", "PushButton"))
        self._button_B.setText(_translate("_game_mode", "PushButton"))
        self._score_label.setText(_translate("_game_mode", "Your score:"))
        self._score.setText(_translate("_game_mode", "0"))
        self._revised_label.setText(_translate("_game_mode", "Revised words"))
