# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_deck.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_add_deck(object):
    def setupUi(self, new_add_deck):
        new_add_deck.setObjectName("new_add_deck")
        new_add_deck.resize(516, 321)
        self.verticalLayout = QtWidgets.QVBoxLayout(new_add_deck)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deck_name = QtWidgets.QGroupBox(new_add_deck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deck_name.sizePolicy().hasHeightForWidth())
        self.deck_name.setSizePolicy(sizePolicy)
        self.deck_name.setStyleSheet("")
        self.deck_name.setObjectName("deck_name")
        self.formLayout = QtWidgets.QFormLayout(self.deck_name)
        self.formLayout.setObjectName("formLayout")
        self.label_deck_name = QtWidgets.QLabel(self.deck_name)
        self.label_deck_name.setObjectName("label_deck_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_deck_name)
        self.deck_name_box = QtWidgets.QLineEdit(self.deck_name)
        self.deck_name_box.setStyleSheet("background-color: #d3d3d3;\n"
"border-radius: 10px;\n"
"border: 1px solid #d3d3d3;\n"
"padding: 5px;")
        self.deck_name_box.setObjectName("deck_name_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deck_name_box)
        self.warning_label = QtWidgets.QLabel(self.deck_name)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.warning_label.setFont(font)
        self.warning_label.setStyleSheet("color: red;")
        self.warning_label.setObjectName("warning_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.warning_label)
        self.verticalLayout.addWidget(self.deck_name)
        self._import_file = QtWidgets.QGroupBox(new_add_deck)
        self._import_file.setStyleSheet("")
        self._import_file.setObjectName("_import_file")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self._import_file)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.importing_radiobutton = QtWidgets.QRadioButton(self._import_file)
        self.importing_radiobutton.setObjectName("importing_radiobutton")
        self.verticalLayout_2.addWidget(self.importing_radiobutton)
        self.import_button = QtWidgets.QPushButton(self._import_file)
        self.import_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_button.sizePolicy().hasHeightForWidth())
        self.import_button.setSizePolicy(sizePolicy)
        self.import_button.setStyleSheet("QPushButton{\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;    \n"
"    background:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #7fc86b;\n"
"    border-color: #7fc86b;\n"
"    color: white;\n"
"}")
        self.import_button.setFlat(False)
        self.import_button.setObjectName("import_button")
        self.verticalLayout_2.addWidget(self.import_button)
        self.imported_file_name = QtWidgets.QLabel(self._import_file)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imported_file_name.sizePolicy().hasHeightForWidth())
        self.imported_file_name.setSizePolicy(sizePolicy)
        self.imported_file_name.setText("")
        self.imported_file_name.setObjectName("imported_file_name")
        self.verticalLayout_2.addWidget(self.imported_file_name)
        self.verticalLayout.addWidget(self._import_file)
        self.frame = QtWidgets.QFrame(new_add_deck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QPushButton{\n"
"    border: 0px;\n"
"    background: #d3d3d3;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    margin-right: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: #a1a1a1;\n"
"    color:white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(297, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_button = QtWidgets.QPushButton(self.frame)
        self.save_button.setStyleSheet("QPushButton{\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 7px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}")
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(self.frame)
        self.cancel_button.setStyleSheet("QPushButton{\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;    \n"
"    background:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #7fc86b;\n"
"    border-color: #7fc86b;\n"
"    color: white;\n"
"}")
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(new_add_deck)
        self.importing_radiobutton.toggled['bool'].connect(self.import_button.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(new_add_deck)

    def retranslateUi(self, new_add_deck):
        _translate = QtCore.QCoreApplication.translate
        new_add_deck.setWindowTitle(_translate("new_add_deck", "Add deck"))
        self.deck_name.setTitle(_translate("new_add_deck", "Deck name"))
        self.label_deck_name.setText(_translate("new_add_deck", "Input deck name:"))
        self.warning_label.setText(_translate("new_add_deck", "The name must not be blank"))
        self._import_file.setTitle(_translate("new_add_deck", "Importing items"))
        self.importing_radiobutton.setText(_translate("new_add_deck", "Importing files (.JSON, .XML and .CSV are supported)"))
        self.import_button.setText(_translate("new_add_deck", "Import from file..."))
        self.save_button.setText(_translate("new_add_deck", "Save"))
        self.cancel_button.setText(_translate("new_add_deck", "Cancel"))
