# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/new_cards_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__new_cards_list(object):
    def setupUi(self, _new_cards_list):
        _new_cards_list.setObjectName("_new_cards_list")
        _new_cards_list.resize(686, 500)
        _new_cards_list.setMinimumSize(QtCore.QSize(650, 500))
        _new_cards_list.setStyleSheet("QGroupBox{\n"
"    background:white;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(_new_cards_list)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(_new_cards_list)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self._button_frame = QtWidgets.QFrame(_new_cards_list)
        self._button_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._button_frame.setObjectName("_button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._button_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self._add_card = QtWidgets.QPushButton(self._button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._add_card.sizePolicy().hasHeightForWidth())
        self._add_card.setSizePolicy(sizePolicy)
        self._add_card.setStyleSheet("QPushButton{\n"
"    border: 0px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    border-radius: 5px;\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}")
        self._add_card.setObjectName("_add_card")
        self.horizontalLayout.addWidget(self._add_card)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self._button_frame)
        self.scrollArea = QtWidgets.QScrollArea(_new_cards_list)
        self.scrollArea.setMinimumSize(QtCore.QSize(550, 0))
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"       border: 0;\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"       border: 0;\n"
"    height: 6px;\n"
"    border-radius: 3px;\n"
"    background: #d3d3d3;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    background: rgb(161, 161, 161);\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed{\n"
"    background-color: rgb(120, 120, 120);\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self._all_cards_area = QtWidgets.QWidget()
        self._all_cards_area.setGeometry(QtCore.QRect(0, 0, 668, 409))
        self._all_cards_area.setMinimumSize(QtCore.QSize(600, 0))
        self._all_cards_area.setObjectName("_all_cards_area")
        self.gridLayout_2 = QtWidgets.QGridLayout(self._all_cards_area)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea.setWidget(self._all_cards_area)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(_new_cards_list)
        QtCore.QMetaObject.connectSlotsByName(_new_cards_list)

    def retranslateUi(self, _new_cards_list):
        _translate = QtCore.QCoreApplication.translate
        _new_cards_list.setWindowTitle(_translate("_new_cards_list", "Deck: "))
        self.label.setText(_translate("_new_cards_list", "Cards list from deck: "))
        self._add_card.setText(_translate("_new_cards_list", "Add card"))
