# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/cards_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__cards_list(object):
    def setupUi(self, _cards_list):
        _cards_list.setObjectName("_cards_list")
        _cards_list.resize(339, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(_cards_list)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._cards_table = QtWidgets.QTableWidget(_cards_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._cards_table.sizePolicy().hasHeightForWidth())
        self._cards_table.setSizePolicy(sizePolicy)
        self._cards_table.setObjectName("_cards_table")
        self._cards_table.setColumnCount(2)
        self._cards_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self._cards_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self._cards_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self._cards_table.setHorizontalHeaderItem(1, item)
        self.horizontalLayout.addWidget(self._cards_table)
        self.frame = QtWidgets.QFrame(_cards_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self._add_card_button = QtWidgets.QPushButton(self.frame)
        self._add_card_button.setObjectName("_add_card_button")
        self.verticalLayout.addWidget(self._add_card_button)
        self._delete_button = QtWidgets.QPushButton(self.frame)
        self._delete_button.setObjectName("_delete_button")
        self.verticalLayout.addWidget(self._delete_button)
        self._edit_button = QtWidgets.QPushButton(self.frame)
        self._edit_button.setObjectName("_edit_button")
        self.verticalLayout.addWidget(self._edit_button)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(_cards_list)
        QtCore.QMetaObject.connectSlotsByName(_cards_list)

    def retranslateUi(self, _cards_list):
        _translate = QtCore.QCoreApplication.translate
        _cards_list.setWindowTitle(_translate("_cards_list", "Cards list from deck: "))
        # item = self._cards_table.verticalHeaderItem(0)
        # item.setText(_translate("_cards_list", "1"))
        item = self._cards_table.horizontalHeaderItem(0)
        item.setText(_translate("_cards_list", "Front"))
        item = self._cards_table.horizontalHeaderItem(1)
        item.setText(_translate("_cards_list", "Back"))
        self._add_card_button.setText(_translate("_cards_list", "Add card"))
        self._delete_button.setText(_translate("_cards_list", "Delete card"))
        self._edit_button.setText(_translate("_cards_list", "Edit card"))
