# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/card_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__card_info(object):
    def setupUi(self, _card_info):
        _card_info.setObjectName("_card_info")
        _card_info.resize(217, 250)
        _card_info.setMinimumSize(QtCore.QSize(217, 250))
        _card_info.setMaximumSize(QtCore.QSize(220, 300))
        _card_info.setStyleSheet("QGroupBox{\n"
"    background: #ffffff;\n"
"    border: 0px;\n"
"    border-radius: 20px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(_card_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self._front = QtWidgets.QLabel(_card_info)
        font = QtGui.QFont()
        font.setPointSize(12)
        self._front.setFont(font)
        self._front.setStyleSheet("background-color: white;")
        self._front.setAlignment(QtCore.Qt.AlignCenter)
        self._front.setObjectName("_front")
        self.verticalLayout.addWidget(self._front)
        self.scrollArea = QtWidgets.QScrollArea(_card_info)
        self.scrollArea.setStyleSheet("background-color: white;")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 199, 79))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self._back = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self._back.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self._back.setFont(font)
        self._back.setAlignment(QtCore.Qt.AlignCenter)
        self._back.setObjectName("_back")
        self.verticalLayout_2.addWidget(self._back)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self._img_frame = QtWidgets.QFrame(_card_info)
        self._img_frame.setStyleSheet("background-color: white;")
        self._img_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._img_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._img_frame.setObjectName("_img_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._img_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._img = QtWidgets.QLabel(self._img_frame)
        self._img.setMinimumSize(QtCore.QSize(50, 50))
        self._img.setMaximumSize(QtCore.QSize(100, 100))
        self._img.setAlignment(QtCore.Qt.AlignCenter)
        self._img.setObjectName("_img")
        self.horizontalLayout.addWidget(self._img)
        self.verticalLayout.addWidget(self._img_frame)
        self.frame = QtWidgets.QFrame(_card_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self._options = QtWidgets.QPushButton(self.frame)
        self._options.setStyleSheet("QPushButton#_options{\n"
"    height: 30px;\n"
"    width: 30px;\n"
"    border-radius: 15px;\n"
"    background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #77bd65, stop: 1 #91e67b );\n"
"}\n"
"\n"
"QPushButton::menu-indicator{\n"
"    width: 0px;\n"
"}\n"
"\n"
"QPushButton#_options:hover{\n"
"    background-color: #81cc6e;\n"
"}\n"
"\n"
"QPushButton#_options:pressed{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 1 #77bd65, stop: 0 #91e67b );\n"
"}")
        self._options.setObjectName("_options")
        self.horizontalLayout_2.addWidget(self._options)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(_card_info)
        QtCore.QMetaObject.connectSlotsByName(_card_info)

    def retranslateUi(self, _card_info):
        _translate = QtCore.QCoreApplication.translate
        _card_info.setWindowTitle(_translate("_card_info", "GroupBox"))
        self._front.setText(_translate("_card_info", "{Front}"))
        self._back.setText(_translate("_card_info", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean semper scelerisque turpis id iaculis. Suspendisse maximus nibh diam, vitae lacinia tellus lacinia sed. "))
        self._img.setText(_translate("_card_info", "{img}"))
        self._options.setText(_translate("_card_info", "..."))
