# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/deck_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__deck_info(object):
    def setupUi(self, _deck_info):
        _deck_info.setObjectName("_deck_info")
        _deck_info.resize(460, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(_deck_info.sizePolicy().hasHeightForWidth())
        _deck_info.setSizePolicy(sizePolicy)
        _deck_info.setMinimumSize(QtCore.QSize(460, 200))
        _deck_info.setMaximumSize(QtCore.QSize(650, 200))
        _deck_info.setStyleSheet("/*QGroupBox{\n"
"    border: 0px; \n"
"    border: 2px solid #91e67b;\n"
"    /*background: #77bc65;\n"
"    border-radius: 10px;\n"
"}*/\n"
"QGroupBox{\n"
"    border: 0px;\n"
"    background: #ffffff;\n"
"    border-radius: 10px;\n"
"}\n"
"QGroupBox:hover{\n"
"    background: rgba(179, 255, 152, 100);\n"
"}\n"
"QLabel{\n"
"    border: 0px;\n"
"}\n"
"QFrame{\n"
"    border: 0px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(_deck_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self._deck_name = QtWidgets.QLabel(_deck_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._deck_name.sizePolicy().hasHeightForWidth())
        self._deck_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self._deck_name.setFont(font)
        self._deck_name.setObjectName("_deck_name")
        self.verticalLayout.addWidget(self._deck_name)
        self._num_of_cards = QtWidgets.QLabel(_deck_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._num_of_cards.sizePolicy().hasHeightForWidth())
        self._num_of_cards.setSizePolicy(sizePolicy)
        self._num_of_cards.setObjectName("_num_of_cards")
        self.verticalLayout.addWidget(self._num_of_cards)
        self._cards_to_review = QtWidgets.QLabel(_deck_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._cards_to_review.sizePolicy().hasHeightForWidth())
        self._cards_to_review.setSizePolicy(sizePolicy)
        self._cards_to_review.setObjectName("_cards_to_review")
        self.verticalLayout.addWidget(self._cards_to_review)
        self._button_frame = QtWidgets.QFrame(_deck_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._button_frame.sizePolicy().hasHeightForWidth())
        self._button_frame.setSizePolicy(sizePolicy)
        self._button_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self._button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._button_frame.setObjectName("_button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self._button_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self._flash_mode = QtWidgets.QPushButton(self._button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._flash_mode.sizePolicy().hasHeightForWidth())
        self._flash_mode.setSizePolicy(sizePolicy)
        self._flash_mode.setStyleSheet("QPushButton{\n"
"    /*background: #d3d3d3;*/\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}\n"
"")
        self._flash_mode.setObjectName("_flash_mode")
        self.horizontalLayout.addWidget(self._flash_mode)
        self._game_mode = QtWidgets.QPushButton(self._button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._game_mode.sizePolicy().hasHeightForWidth())
        self._game_mode.setSizePolicy(sizePolicy)
        self._game_mode.setStyleSheet("QPushButton{\n"
"    /*background: #d3d3d3;*/\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}")
        self._game_mode.setObjectName("_game_mode")
        self.horizontalLayout.addWidget(self._game_mode)
        self._view_cards_list = QtWidgets.QPushButton(self._button_frame)
        self._view_cards_list.setStyleSheet("QPushButton{\n"
"    /*background: #d3d3d3;*/\n"
"    border: 2px solid #91e67b;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}")
        self._view_cards_list.setObjectName("_view_cards_list")
        self.horizontalLayout.addWidget(self._view_cards_list)
        self._more_funcs = QtWidgets.QToolButton(self._button_frame)
        self._more_funcs.setStyleSheet("QToolButton{\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    /*padding-left: 10px;\n"
"    padding-right: 10px;*/\n"
"}\n"
"\n"
"QToolButton::menu-indicator{\n"
"    width: 0px;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: #91e67b;\n"
"    color: white;\n"
"}\n"
"")
        self._more_funcs.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self._more_funcs.setObjectName("_more_funcs")
        self.horizontalLayout.addWidget(self._more_funcs)
        self.verticalLayout.addWidget(self._button_frame)

        self.retranslateUi(_deck_info)
        QtCore.QMetaObject.connectSlotsByName(_deck_info)

    def retranslateUi(self, _deck_info):
        _translate = QtCore.QCoreApplication.translate
        _deck_info.setWindowTitle(_translate("_deck_info", "GroupBox"))
        self._deck_name.setText(_translate("_deck_info", "Deck_name"))
        self._num_of_cards.setText(_translate("_deck_info", "0 cards"))
        self._cards_to_review.setText(_translate("_deck_info", "0 cards to review"))
        self._flash_mode.setText(_translate("_deck_info", "Flashcards mode"))
        self._game_mode.setText(_translate("_deck_info", "Game mode"))
        self._view_cards_list.setText(_translate("_deck_info", "View cards list"))
        self._more_funcs.setText(_translate("_deck_info", "..."))
